---
# tasks file for hw15_3

- name: create users for node_exporter & prometheus
  user:
    name: "{{  item  }}"
    create_home: no
    shell: /bin/false
  loop:
    - node_exporter
    - prometheus

- name: create temp folders
  file:
    path: "{{  item  }}"
    state: directory
  loop:
    - /tmp/node_exporter
    - /tmp/prometheus
    - /tmp/grafana

- name: create not temp folders
  file:
    path: "{{  item  }}"
    owner: prometheus 
    group: prometheus
    state: directory
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

# deploy no_exporter
- name: download node_exporter archive
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter/

- name: unzip node_exporter gz
  unarchive:
    src: /tmp/node_exporter/node_exporter-1.3.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter/
    remote_src: yes

- name: copy node_exporter binary file
  copy:
    src: /tmp/node_exporter/node_exporter-1.3.1.linux-amd64/node_exporter
    dest: /usr/local/bin/
    mode: '0755'
    remote_src: yes

- name: create node_exporter service unit
  copy: 
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: systemctl node_exporter daemon_reload & service start
  systemd:
    daemon_reload: yes
    name: node_exporter.service
    enabled: yes
    state: started

# deploy prometheus
- name: download prometeheus archive.gz
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.32.1/prometheus-2.32.1.linux-amd64.tar.gz
    dest: /tmp/prometheus/

- name: unarchive prometheus gz
  unarchive:
    src: /tmp/prometheus/prometheus-2.32.1.linux-amd64.tar.gz
    dest: /tmp/prometheus/
    remote_src: yes

- name: copy prometheus binary 
  copy: 
    src: "{{  item  }}"
    dest: /usr/local/bin/
    mode: '0755'
    remote_src: yes
  loop:
    - /tmp/prometheus/prometheus-2.32.1.linux-amd64/prometheus
    - /tmp/prometheus/prometheus-2.32.1.linux-amd64/promtool

- name: copy prometheus folders
  copy:
    src: "{{  item  }}"
    dest: /etc/prometheus
    remote_src: yes
  loop:
    - /tmp/prometheus/prometheus-2.32.1.linux-amd64/consoles
    - /tmp/prometheus/prometheus-2.32.1.linux-amd64/console_libraries
 
- name: copy prometheus conf
  copy:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml

- name: create prometheus service unit
  copy: 
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service

- name: systemctl prometheus daemon_reload & service start
  systemd:
    daemon_reload: yes
    name: prometheus.service
    enabled: yes
    state: started

# deploy grafana
- name: download grafana rpm 
  get_url:
    url: https://dl.grafana.com/enterprise/release/grafana-enterprise-8.3.4-1.x86_64.rpm
    dest: /tmp/grafana

- name: install grafana
  yum:
    name: /tmp/grafana/grafana-enterprise-8.3.4-1.x86_64.rpm 
    state: present

- name: grafana service start
  systemd:
    name: grafana-server.service
    enabled: yes
    state: started
