---

- name: disable selinux
  shell: setenforce 0

- name: set up forward packages across routers
  sysctl:
    name: net.ipv4.conf.all.forwarding
    value: '1'
    state: present
  loop:
    - net.ipv4.conf.all.forwarding
    - net.ipv4.ip_forward

- name: install default utils
  yum:
    name: "{{  item  }}"
    state: latest
  loop:
    - htop
    - iperf3
    - tree
    - vim
    - tcpdump
    - openvpn
    - easy-rsa

- name: create openvpn static.key
  shell: openvpn --genkey --secret /etc/openvpn/static.key
  when:
    - ansible_hostname == "server"


- name: copy to localhost static.key
  fetch:
    src: /etc/openvpn/static.key
    dest: /home/nbt/otus/hw22/roles/tap/files/
    flat: yes
  when:
    - ansible_hostname == "server"

- name: copy static.key to client
  copy:
    src: static.key
    dest: /etc/openvpn/static.key
  when:
    - ansible_hostname == "client"

- name: copy openvpn conf to server
  template:
    src: tap-server.conf.j2
    dest: /etc/openvpn/server.conf
    owner: root
    mode: 0644
  tags:
    - conf

- name: start openvpn-server
  service:
    name: openvpn@server
    state: started
    enabled: yes
