# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
  end

  config.vm.define "ipaserver" do |ipaserver|
    ipaserver.vm.network "private_network", ip: "192.168.56.10", mask: "255.255.255.0"
    ipaserver.vm.hostname = "ipaserver"
    ipaserver.vm.provider :virtualbox do |vb|
#      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.memory = 2048
      vb.cpus = 2
    end
  end

  config.vm.define "ipaclient" do |ipaclient|
    ipaclient.vm.network "private_network", ip: "192.168.56.20", mask: "255.255.255.0"
    ipaclient.vm.hostname = "ipaclient"
  end

  config.vm.provision "file", source: "files/authorized_keys", destination: "~/authorized_keys"
  config.vm.provision "shell", path: "files/start.sh"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbooks/default.yml"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbooks/ipaserver.yml"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbooks/ipaclient.yml"
  end
end
