hw18gr:
    hosts:
        inetRouter:
            ansible_host: 192.168.56.11
        centralRouter:
            ansible_host: 192.168.56.12
        testServer1:
            ansible_host: 192.168.56.13
        testClient1:
            ansible_host: 192.168.56.14
        testServer2:
            ansible_host: 192.168.56.15
        testClient2:
            ansible_host: 192.168.56.16
