hw25gr:
    hosts:
        ipaserver:
            ansible_host: 192.168.56.10
            ipa_hostname: ipaserver
        ipaclient:
            ansible_host: 192.168.56.20
            ipa_hostname: ipaclient
            