Vagrant.configure("2") do |config|
  # Base VM OS configuration.
  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01"
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.cpus = 1
  end
  # Define two VMs with static private IP addresses.
  boxes = [
    { :name => "web",
    :ip => "192.168.50.10",
    },
    { :name => "log",
    :ip => "192.168.50.15",
    }
  ]
  # Provision each of the VMs.
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip: opts[:ip]
    end
  end
  config.vm.provision "file", source: "files/authorized_keys", destination: "~/authorized_keys"
  config.vm.provision "shell", path: "./scripts/start.sh"
  config.vm.provision "shell", inline: <<-SHELL
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY* |\
    yum install -y epel-release python39
    SHELL
  config.vm.provision "ansible" do |ansible|    
    ansible.playbook = "./playbooks/hw16_role.yml"
  end
  config.vm.define :web do |web|
    web.vm.provision "ansible" do |ansible|    
      ansible.playbook = "./playbooks/web_role.yml"
    end
  config.vm.define :log do |log|
    web.vm.provision "ansible" do |ansible|    
      ansible.playbook = "./playbooks/log_role.yml"
    end
  end  
  end
end
