---
# tasks file for everyone
- name: Stop service firewalld, if started
  ansible.builtin.service:
    name: firewalld
    state: stopped

- name: add users
  ansible.builtin.user:
    name: "{{ item }}"
    password: "{{ upassword | password_hash('sha512') }}"
    shell: /bin/bash
    state: present
  loop:
    - day
    - friday

- name: install many utils
  yum: 
    name: "{{ item }}"
    state: latest
  loop:
    - setools-console 
    - policycoreutils-python
    - vim
    - nmap-ncat

- name: allow ssh-connect by password
  ansible.builtin.replace:
    path: /etc/ssh/sshd_config 
    regexp: 'PasswordAuthentication no'
    replace: 'PasswordAuthentication yes'

- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: disable ntp
  ansible.builtin.shell:
    cmd: timedatectl set-ntp 0

- name: set date
  ansible.builtin.shell:
    cmd: timedatectl set-time 2022-01-09
