- name: delete default route
  shell: ip route delete "{{  item  }}"
  loop:
    - default

- name: set up forward packages across routers
  sysctl:
    name: net.ipv4.conf.all.forwarding
    value: '1'
    state: present

- name: copy network_cfg 
  template:
    src: 50-vagrant.yaml.j2
    dest: /etc/netplan/50-vagrant.yaml
  notify:
    - restart_network