---
- name: Check current docker-compose version.
  command: "{{ docker_compose_path }} --version"
  register: docker_compose_current_version
  check_mode: false
  changed_when: false
  failed_when: false

#- name: Delete existing docker-compose version if it's different.
#  file:
#    path: "{{ docker_compose_path }}"
#    state: absent
#  when: >
#    docker_compose_current_version.stdout is defined
#    and docker_compose_version not in docker_compose_current_version.stdout
#  failed_when: false

- name: Install Docker Compose (if configured).
  get_url:
    url: "{{ docker_compose_url }}"
    dest: "{{ docker_compose_path }}"
    mode: 0755
#  when: >
#    docker_compose_current_version.stdout is not defined
#    or docker_compose_version not in docker_compose_current_version.stdout

- name: Add docker-compose to global PATH
  ansible.builtin.lineinfile:
    path: "{{  path_profile }}"
    line: "{{  path_docker_compose }}"
    create: yes
