hw21gr:
    hosts:
        router1:
            ansible_host: 192.168.50.10
            router_id: 1.1.1.1
            description_1: r1-r2
            description_2: r1-r3
            description_3: net_router1
            ip_1: 10.0.10.0/30
            ip_2: 10.0.12.0/30
            ip_3: 192.168.10.1/24
            network_1: 10.0.10.0/30
            network_2: 10.0.12.0/30
            network_3: 192.168.10.0/24
            neighbor_1: 10.0.10.2
            neighbor_2: 10.0.12.2
        router2:
            ansible_host: 192.168.50.11
            router_id: 2.2.2.2
            description_1: r1-r2
            description_2: r2-r3
            description_3: net_router2
            ip_1: 10.0.10.2/30
            ip_2: 10.0.11.2/30
            ip_3: 192.168.20.1/24
            network_1: 10.0.10.0/30
            network_2: 10.0.11.0/30
            network_3: 192.168.20.0/24
            neighbor_1: 10.0.10.1
            neighbor_2: 10.0.11.1
        router3:
            ansible_host: 192.168.50.12
            router_id: 3.3.3.3
            description_1: r2-r3
            description_2: r1-r3
            description_3: net_router3
            ip_1: 10.0.11.1/30
            ip_2: 10.0.12.2/30
            ip_3: 192.168.30.1/24
            network_1: 10.0.11.0/30
            network_2: 10.0.12.0/30
            network_3: 192.168.30.0/24
            neighbor_1: 10.0.11.2
            neighbor_2: 10.0.12.1
