hw20gr:
    hosts:
        inetRouter:
            ansible_host: 192.168.50.11
        centralRouter:
            ansible_host: 192.168.50.12
        centralServer:
            ansible_host: 192.168.50.13
        inetRouter2:
            ansible_host: 192.168.50.14
