---

- name: create folder for images
  file:
    path: "{{  item  }}"
    state: directory
    mode: 0755
  loop:
    - /images
    - /iso

- name: make xfs on sdb
  filesystem:
    dev: /dev/sdb
    fstype: xfs

- name: mount /dev/sdb to /images
  mount:
    path: /images
    src: /dev/sdb
    state: mounted
    fstype: xfs

- name: copy boot.iso&dvd.iso
  copy: 
    src: "{{  item  }}"
    dest: /images
    owner: vagrant
    group: vagrant
  loop:
    - /home/nbt/otus/hw19/files/CentOS-8.4.2105-x86_64-boot.iso
    - /home/nbt/otus/hw19/files/CentOS-8.4.2105-x86_64-dvd1.iso

#- name: mount dvd1.iso to /mnt
#  shell: umount /mnt && mount -t iso9660 /images/CentOS-8.4.2105-x86_64-dvd1.iso /mnt -o loop,ro

- name: Mount ISO image
  mount:
    path: /mnt
    src: /images/CentOS-8.4.2105-x86_64-dvd1.iso
    fstype: iso9660
    opts: ro,loop
    state: mounted

- name: copy /mnt to /iso
  copy: 
    src: /mnt/
    dest: /iso/
    remote_src: true

- name: install utils
  yum:
    name: "{{  item  }}"
    state: latest
  loop:
    - httpd
    - policycoreutils-python-utils
    - setroubleshoot
    - vim
    - wget
    - epel-release
    - tftp-server
    - dhcp-server

- name: start httpd
  service:
    name: httpd
    enabled: true
    state: started

- name: copy apache conf
  copy:
    src:  pxeboot.conf.j2
    dest: /etc/httpd/conf.d/pxeboot.conf
    owner: root
    group: root
    mode: 0640
  notify:
    - restart_httpd

- name: firewalld allow http,tftp
  firewalld:
    service: "{{  item  }}"
    permanent: yes
    state: enabled
  loop:
    - http
    - tftp
  notify:
    - restart_firewalld

- name: allow apache any dir in selinux
  shell: setenforce 0

#Создаём каталог /var/lib/tftpboot/pxelinux.cfg
- name: Create TFTP directory
  file:
    path: /var/lib/tftpboot/pxelinux.cfg
    state: directory
    mode: '0755'

#Копируем файл-меню на сервер
- name: set up pxelinux
  copy:
    src: default
    dest: /var/lib/tftpboot/pxelinux.cfg/default
    owner: root
    group: root
    mode: 0644

#Извлекаем файлы из RPM-пакета
- name: extract packages syslinux
  shell: rpm2cpio /iso/BaseOS/Packages/syslinux-tftpboot-6.04-5.el8.noarch.rpm | cpio -dimv

#Копируем файлы в каталог /var/lib/tftpboot/
- name: copy files to TFTP share
  copy:
    src: /root/tftpboot/{{ item }}
    dest: /var/lib/tftpboot/{{ item }}
    mode: 0644
    remote_src: true
  loop:
    - pxelinux.0
    - ldlinux.c32
    - libmenu.c32
    - libutil.c32
    - menu.c32
    - vesamenu.c32

#Копируем файлы в каталог /var/lib/tftpboot/
- name: copy initrd and vmlinuz files to TFTP share
  copy:
    src: /iso/images/pxeboot/{{ item }}
    dest: /var/lib/tftpboot/{{ item }}
    mode: 0755
    remote_src: true
  loop:
    - initrd.img
    - vmlinuz

#Перезапускаем TFTP-сервер и добавляем его в автозагрузку
- name: restart tftp-server
  service:
    name: tftp.service
    state: restarted
    enabled: true

#Копирование файла конфигурации DHCP-сервера
- name: set up dhcp-server
  copy:
    src: dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
    mode: 0644

#Start dhcp-server    
- name: start dhcp-server
  service:
    name: dhcpd
    enabled: yes
    state: started

- name: copy ks.cfg
  copy:
    src: ks.cfg
    dest: /iso/ks.cfg
    owner: root
    group: root
    mode: 0755
  notify:
    - restart_dhcpd