hw18gr:
    hosts:
        inetRouter:
            ansible_host: 192.168.50.11
        centralRouter:
            ansible_host: 192.168.50.12
        centralServer:
            ansible_host: 192.168.50.13
        office1Router:
            ansible_host: 192.168.50.14
        office1Server:
            ansible_host: 192.168.50.15
        office2Router:
            ansible_host: 192.168.50.16
        office2Server:
            ansible_host: 192.168.50.17
router_gr:
    hosts:
        inetRouter:
            ansible_host: 192.168.50.11
        centralRouter:
            ansible_host: 192.168.50.12
        office1Router:
            ansible_host: 192.168.50.14
        office2Router:
            ansible_host: 192.168.50.16
