- name: set eth1 config
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces

- name: delete default route
  shell: ip route delete "{{  item  }}"
  loop:
    - default

- name: add new default route
  shell:  'ip route add 0.0.0.0/0 via 192.168.255.5'
  
- name: set up forward packages across routers
  sysctl:
    name: net.ipv4.conf.all.forwarding
    value: '1'
    state: present

- name: Reboot host and wait for it to restart
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
    