# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
        :hw13 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
        },
}

Vagrant.configure("2") do |config|
        MACHINES.each do |boxname, boxconfig|
                config.vm.define boxname do |box|
                        box.vm.box = boxconfig[:box_name]
                        box.vm.host_name = boxname.to_s
                        #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
                        box.vm.network "private_network", ip: boxconfig[:ip_addr]
                        box.vm.provider :virtualbox do |vb|
                                vb.customize ["modifyvm", :id, "--memory", "256"]
                        end
                        box.vm.provision "file", source: "files/authorized_keys", destination: "~/authorized_keys"
                        box.vm.provision "shell", path: "./scripts/start.sh"
                        box.vm.provision "shell", inline: <<-SHELL
                                rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY* |\
                                yum install -y epel-release python39
                                SHELL
                        box.vm.provision "ansible" do |ansible|    
                                ansible.playbook = "playbooks/hw13.yml"
                        end
                end
        end
end
