# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :inetRouter => {
        :box_name => "centos/7",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "ir-cr"},
                   {ip: '192.168.50.11', adapter: 8},
                ]
  },
  :centralRouter => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "ir-cr"},
                   {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "cr-cs"},
                   {ip: '192.168.255.6', adapter: 4, netmask: "255.255.255.252", virtualbox__intnet: "ir2-cr"},
                   {ip: '192.168.50.12', adapter: 8},
                ]
  },
  
  :centralServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "cr-cs"},
                   {ip: '192.168.50.13', adapter: 8}, 
                ]
  },
  :inetRouter2 => {
        :box_name => "centos/7",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '192.168.255.5', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "ir2-cr"},
                   {ip: '192.168.50.14', adapter: 8},
                ]
  },  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "inetRouter"
          box.vm.provision "file", source: "files/authorized_keys", destination: "~/authorized_keys"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sudo echo $(cat /home/vagrant/authorized_keys) >>/root/.ssh/authorized_keys
            rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY*
            yum install -y epel-release python36
            SHELL
          box.vm.provision "ansible" do |ansible|    
            ansible.playbook = "./playbooks/inetRouter.yml"
          end
        when "centralRouter"
          box.vm.provision "file", source: "files/authorized_keys", destination: "~/authorized_keys"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sudo echo $(cat /home/vagrant/authorized_keys) >>/root/.ssh/authorized_keys
            rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY*
            yum install -y epel-release python36
            SHELL
          box.vm.provision "ansible" do |ansible|    
            ansible.playbook = "./playbooks/centralRouter.yml"
          end
        when "centralServer"
          box.vm.provision "file", source: "files/authorized_keys", destination: "~/authorized_keys"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sudo echo $(cat /home/vagrant/authorized_keys) >>/root/.ssh/authorized_keys
            rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY*
            yum install -y epel-release python36
            SHELL
          box.vm.provision "ansible" do |ansible|    
            ansible.playbook = "./playbooks/centralServer.yml"
          end
        when "inetRouter2"
          box.vm.provision "file", source: "files/authorized_keys", destination: "~/authorized_keys"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sudo echo $(cat /home/vagrant/authorized_keys) >>/root/.ssh/authorized_keys
            rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY*
            yum install -y epel-release python36
            SHELL
          box.vm.provision "ansible" do |ansible|    
            ansible.playbook = "./playbooks/inetRouter2.yml"
          end
        end
      end
  end
end
