---
# tasks file for everyone

- name: begin role for everyone
  debug:
    msg: "!!!!!   EVERYONE ROLE BEGINNING   !!!!!"

- name: start # Stop service firewalld, if started
  ansible.builtin.service:
    name: firewalld
    state: started

#- name: add users
#  ansible.builtin.user:
#    name: "{{ item }}"
#    password: "{{ upassword | password_hash('sha512') }}"
#    shell: /bin/bash
#    state: present
#  loop:
#    - dock
#
- name: install many utils
  yum: 
    name: "{{ item }}"
    state: latest
  loop:
    - setools-console 
    - policycoreutils-python
    - vim
    - nmap-ncat
    - tree
    - bind-utils
    - wget
    - nc
    - git
    
#- name: allow ssh-connect by password
#  ansible.builtin.replace:
#    path: /etc/ssh/sshd_config 
#    regexp: 'PasswordAuthentication no'
#    replace: 'PasswordAuthentication yes'
#
- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

# tasks install docker

- name: Remove old docker
  yum:
    name: docker*
    state: absent

- name: Install yum utils
  yum:
    name: yum-utils
    state: latest

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: install docker
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user day to docker group
  user:
    name: dock
    groups: docker
    append: yes

# install docker-compose

- name: Check current docker-compose version.
  command: "{{ docker_compose_path }} --version"
  register: docker_compose_current_version
  check_mode: false
  changed_when: false
  failed_when: false

#- name: Delete existing docker-compose version if it's different.
#  file:
#    path: "{{ docker_compose_path }}"
#    state: absent
#  when: >
#    docker_compose_current_version.stdout is defined
#    and docker_compose_version not in docker_compose_current_version.stdout
#  failed_when: false

- name: Install Docker Compose (if configured).
  get_url:
    url: "{{ docker_compose_url }}"
    dest: "{{ docker_compose_path }}"
    mode: 0755
#  when: >
#    docker_compose_current_version.stdout is not defined
#    or docker_compose_version not in docker_compose_current_version.stdout

- name: Add docker-compose to global PATH
  ansible.builtin.lineinfile:
    path: "{{  path_profile }}"
    line: "{{  path_docker_compose }}"
    create: yes

- name: set timezone
  community.general.timezone:
    name: Europe/Moscow
 