hw22gr:
    hosts:
        server:
            ansible_host: 192.168.10.10            
        client:
            ansible_host: 192.168.10.20
key_group:
    hosts:
        client:
            ansible_host: 192.168.10.20
                            