# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetRouter => {
        :box_name => "centos/7",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.50.11', adapter: 8},
                ]
  },
  :centralRouter => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   {ip: '192.168.0.33', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
                   {ip: '192.168.0.65', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mgt-net"},
                   {ip: '192.168.255.5', adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "office2-central"},
                   {ip: '192.168.255.9', adapter: 7, netmask: "255.255.255.252", virtualbox__intnet: "office1-central"},
                   {ip: '192.168.50.12', adapter: 8},
                ]
  },
  
  :centralServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   {ip: '192.168.50.13', adapter: 8}, 
                ]
  },
  :office1Router => {
        :box_name => "ubuntu/focal64",
        :net => [
                   {ip: '192.168.255.10', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "office1-central"},
                   {ip: '192.168.2.1', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "office1-dev"},
                   {ip: '192.168.2.65', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "office1-testsrv"},
                   {ip: '192.168.2.129', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "office1-managers"},
                   {ip: '192.168.2.193', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "office1-hw"},
                   {ip: '192.168.50.14', adapter: 8}, 
                ]
  },
  :office1Server => {
        :box_name => "ubuntu/focal64",
        :net => [
                   {ip: '192.168.2.130', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "office1-managers"},
                   {ip: '192.168.50.15', adapter: 8}, 
                ]
  },
  :office2Router => {
        :box_name => "debian/bullseye64",
        :net => [
                   {ip: '192.168.255.6', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "office2-central"},
                   {ip: '192.168.1.1', adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "office2-dev"},
                   {ip: '192.168.1.129', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "office2-testsrv"},
                   {ip: '192.168.1.193', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "office2-wf"},
                   {ip: '192.168.50.16', adapter: 8}, 
                ]
  },
  :office2Server => {
        :box_name => "debian/bullseye64",
        :net => [
                   {ip: '192.168.1.2', adapter: 2, netmask: "255.255.255.128", virtualbox__intnet: "office2-dev"},
                   {ip: '192.168.50.17', adapter: 8}, 
                ]
  },  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "inetRouter"
          box.vm.provision "file", source: "files/authorized_keys", destination: "~/authorized_keys"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sudo echo $(cat /home/vagrant/authorized_keys) >>/root/.ssh/authorized_keys
            rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY*
            yum install -y epel-release python36
            SHELL
          box.vm.provision "ansible" do |ansible|    
            ansible.playbook = "./playbooks/inetRouter.yml"
          end        
        when "centralRouter"
          box.vm.provision "file", source: "files/authorized_keys", destination: "~/authorized_keys"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sudo echo $(cat /home/vagrant/authorized_keys) >>/root/.ssh/authorized_keys
            rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY*
            yum install -y epel-release python36
            SHELL
          box.vm.provision "ansible" do |ansible|    
            ansible.playbook = "./playbooks/centralRouter.yml"
          end        
        when "centralServer"
          box.vm.provision "file", source: "files/authorized_keys", destination: "~/authorized_keys"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sudo echo $(cat /home/vagrant/authorized_keys) >>/root/.ssh/authorized_keys
            rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY*
            yum install -y epel-release python36
            SHELL
          box.vm.provision "ansible" do |ansible|    
            ansible.playbook = "./playbooks/centralServer.yml"
          end        
        when "office1Router"
          box.vm.provision "file", source: "files/authorized_keys", destination: "~/authorized_keys"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sudo echo $(cat /home/vagrant/authorized_keys) >>/root/.ssh/authorized_keys
            SHELL
          box.vm.provision "ansible" do |ansible|    
            ansible.playbook = "./playbooks/office1Router.yml"
          end        
        when "office1Server"
          box.vm.provision "file", source: "files/authorized_keys", destination: "~/authorized_keys"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sudo echo $(cat /home/vagrant/authorized_keys) >>/root/.ssh/authorized_keys
            SHELL
          box.vm.provision "ansible" do |ansible|    
            ansible.playbook = "./playbooks/office1Server.yml"
          end        
        when "office2Router"
          box.vm.provision "file", source: "files/authorized_keys", destination: "~/authorized_keys"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sudo echo $(cat /home/vagrant/authorized_keys) >>/root/.ssh/authorized_keys
            SHELL
          box.vm.provision "ansible" do |ansible|    
            ansible.playbook = "./playbooks/office2Router.yml"
          end        
        when "office2Server"
          box.vm.provision "file", source: "files/authorized_keys", destination: "~/authorized_keys"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sudo echo $(cat /home/vagrant/authorized_keys) >>/root/.ssh/authorized_keys
            apt-get update && sudo apt-get upgrade -y
            SHELL
          box.vm.provision "ansible" do |ansible|    
            ansible.playbook = "./playbooks/office2Server.yml"
          end        
        end

      end

  end
  
  
end
